{% set name = "litellm" %}
{% set version = "1.49.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/litellm-{{ version }}.tar.gz
  sha256: cd82b332e11d80bd7e8b866b407bfbda8afe8bcf109687be5747f0f85f09c74a

build:
  entry_points:
    - litellm = litellm:run_server
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core
    - wheel
    - pip
  run:
    - python >=3.8.1,<4.0,!=3.9.7
    - openai >=1.51.0
    - python-dotenv >=0.2.0
    - tiktoken >=0.7.0
    - importlib-metadata >=6.8.0
    - tokenizers
    - click
    - jinja2 >=3.1.2,<4.0.0
    - aiohttp
    - requests >=2.31.0,<3.0.0
    - pydantic >=2.0.0,<3.0.0
    - jsonschema >=4.22.0,<5.0.0
  run_constrained:
    - uvicorn >=0.22.0,<0.23.0
    - gunicorn >=22.0.0,<23.0.0
    - fastapi >=0.111.0,<1.0.0
    - backoff *
    - pyyaml >=6.0.1,<7.0.0
    - rq *
    - orjson >=3.9.7,<4.0.0
    - apscheduler >=3.10.4,<4.0.0
    - fastapi-sso >=0.10.0,<0.11.0
    - PyJWT >=2.8.0,<3.0.0
    - python-multipart >=0.0.9,<0.0.10
    - cryptography 42.0.5
    - prisma >=0.11.0,<0.12.0
    - azure-identity >=1.15.0,<2.0.0
    - azure-keyvault-secrets >=4.8.0,<5.0.0
    - google-cloud-kms >=2.21.3,<3.0.0
    - resend >=0.8.0,<1.0.0
    - pynacl >=1.5.0,<2.0.0

test:
  imports:
    - litellm
  commands:
    - pip check
    - litellm --help
  requires:
    - pip

about:
  summary: Library to easily interface with LLM API providers
  home: https://github.com/BerriAI/litellm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
