{% set name = "litellm" %}
{% set version = "1.81.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/litellm-{{ version }}.tar.gz
  sha256: fc55aceafda325bd5f704ada61c8be5bd322e6dfa5f8bdcab3290b8732c5857e

build:
  entry_points:
    - litellm = litellm:run_server
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - wheel
    - pip
  run:
    - fastuuid >=0.13.0
    - grpcio >=1.62.3,!=1.68.*,!=1.69.*,!=1.70.*,!=1.71.0,!=1.71.1,!=1.72.0,!=1.72.1,!=1.73.0
    - httpx >=0.23.0
    - python >={{ python_min }}
    - openai >=2.8.0
    - python-dotenv >=0.2.0
    - tiktoken >=0.7.0
    - importlib-metadata >=6.8.0
    - tokenizers
    - click
    - jinja2 >=3.1.2,<4.0.0
    - aiohttp >=3.10
    - pydantic >=2.5.0,<3.0.0
    - jsonschema >=4.23.0,<5.0.0
  run_constrained:
    - uvicorn >=0.31.1,<0.32.0
    - uvloop >=0.21.0,<0.22.0
    - gunicorn >=23.0.0,<24.0.0
    - fastapi >=0.120.1
    - pyyaml >=6.0.1,<7.0.0
    - orjson >=3.9.7,<4.0.0
    - apscheduler >=3.10.4,<4.0.0
    - pyjwt >=2.10.1,<3.0.0
    - python-multipart >=0.0.18,<0.0.19
    - azure-identity >=1.15.0,<2.0.0
    - azure-keyvault-secrets >=4.8.0,<5.0.0
    - azure-storage-blob >=12.25.1,<13.0.0
    - google-cloud-kms >=2.21.3,<3.0.0
    - google-cloud-iam >=2.19.1,<3.0.0
    - google-cloud-aiplatform >=1.38.0
    - pynacl >=1.5.0,<2.0.0
    - websockets >=15.0.1,<16.0.0
    - boto3 =1.40.76
    - mcp >=1.25.0,<2.0.0
    - a2a-sdk >=0.3.22
    - rich =13.7.1
    - diskcache >=5.6.1,<6.0.0
    - polars >=1.31.0,<2.0.0
    - semantic-router >=0.1.12
    - mlflow >3.1.4
    - soundfile >=0.12.1,<0.13.0
    # not yet available on conda-forge
    - prisma >=0.11.0,<0.12.0
    - resend >=0.8.0
    - fastapi-sso >=0.16.0,<0.17.0
    - redisvl >=0.4.1,<0.5.0
    - litellm-proxy-extras =0.4.25
    - litellm-enterprise =0.1.27

test:
  imports:
    - litellm
  commands:
    - pip check
    - litellm --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Library to easily interface with LLM API providers
  home: https://github.com/BerriAI/litellm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - m-rossi
    - jan-janssen
