{% set name = "litellm" %}
{% set version = "1.74.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/litellm-{{ version }}.tar.gz
  sha256: d73bdc6beedfe9ca985ca0e78e27677a8725ca1100e4560d20ebef6e0f62204e

build:
  entry_points:
    - litellm = litellm:run_server
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - wheel
    - pip
  run:
    - httpx >=0.23.0
    - python >={{ python_min }}
    - openai >=1.68.2
    - python-dotenv >=0.2.0
    - tiktoken >=0.7.0
    - importlib-metadata >=6.8.0
    - tokenizers
    - click
    - jinja2 >=3.1.2,<4.0.0
    - aiohttp >=3.10
    - pydantic >=2.5.0,<3.0.0
    - jsonschema >=4.22.0,<5.0.0
  run_constrained:
    - uvicorn >=0.29.0,<0.30.0
    - uvloop >=0.21.0,<0.22.0
    - gunicorn >=23.0.0,<24.0.0
    - fastapi >=0.115.5,<1.0.0
    - pyyaml >=6.0.1,<7.0.0
    - orjson >=3.9.7,<4.0.0
    - apscheduler >=3.10.4,<4.0.0
    - pyjwt >=2.8.0,<3.0.0
    - python-multipart >=0.0.18,<0.0.19
    - cryptography >=43.0.1,<44.0.0
    - azure-identity >=1.15.0,<2.0.0
    - azure-keyvault-secrets >=4.8.0,<5.0.0
    - google-cloud-kms >=2.21.3,<3.0.0
    - pynacl >=1.5.0,<2.0.0
    - websockets >=13.1.0,14.0.0
    - boto3 >=1.34.34,<2.0.0
    - mcp >=1.9.3,<2.0.0
    - rich >13.7.1,<14.0.0
    - diskcache >=5.6.1,<6.0.0
    # not yet available on conda-forge
    - prisma >=0.11.0,<0.12.0
    - resend >=0.8.0,<0.9.0
    - fastapi-sso >=0.16.0,<0.17.0
    - redisvl >=0.4.1,<0.5.0
    - litellm-proxy-extras >=0.2.6,<0.3.0
    - litellm-enterprise >=0.1.10,<0.2.0

test:
  imports:
    - litellm
  commands:
    - pip check
    - litellm --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Library to easily interface with LLM API providers
  home: https://github.com/BerriAI/litellm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - m-rossi
    - jan-janssen
